spring:
  profiles:
    active:
      - dog
      - EN
      - prod

guru:
  username: YmlUserName
  password: YmlPassword
  jdbc-url: YmlUrl

---
spring:
  profiles: prod
guru:
  username: ProdYmlUserName
  password: ProdYmlPassword
  jdbc-url: ProdYmlUrl